services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: pharmastock
      POSTGRES_USER: pharmastock
      POSTGRES_PASSWORD: pharmastock
    ports:
      - "5432:5432"
    volumes:
      - pharmastock-postgres:/var/lib/postgresql/data

volumes:
  pharmastock-postgres: